name: Node.js CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.12.2
      uses: actions/setup-node@v3
      with:
        node-version: 20.12.2
        cache: 'npm'

    - name: Clean previous build
      run: rm -rf build

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Lint code
      run: npm run lint --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.12.2
      uses: actions/setup-node@v3
      with:
        node-version: 20.12.2

    - name: Install dependencies
      run: npm ci

    - name: Deploy to GitHub Pages
      run: |
        npm run build
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f build
        git commit -m "Deploy to GitHub Pages"
        git push origin `git subtree split --prefix build main`:gh-pages --force
